#!/bin/bash
set -e # immediately if a command exits with a non-zero status.

source config

PKG+=" uhttpd"
PKG+=" php7"
PKG+=" php7-cgi"
PKG+=" openssh-sftp-server"
PKG+=" iwinfo"
PKG+=" rsync"
PKG+=" kmod-usb-acm"
PKG+=" kmod-usb-serial-ch341"
# PKG+=" libstdcpp"
PKG+=" print3d"
PKG+=" avahi-daemon-service-http"

make -C imagebuilder image PROFILE=${DEVICE} PACKAGES="$PKG" FILES=../files

ls -R imagebuilder/bin/targets/${ARCH}/${VARIANT}

firmware=imagebuilder/bin/targets/${ARCH}/${VARIANT}/openwrt-${RELEASE}-${ARCH}-${VARIANT}-${DEVICE}-squashfs-sysupgrade.bin

ln -fs "../$firmware" bin/
ln -fs "../$firmware" bin/latest.bin
