#!/bin/bash
set -e # exit in case of errors
source config

echo preparing 'sdk'...
if [ ! -e sdk ]; then
  mkdir sdk
  wget -qO- $SDK_URL | xz -d | tar x --strip-components=1 -C sdk
fi

echo preparing 'imagebuilder'...
if [ ! -e imagebuilder ]; then
  mkdir imagebuilder
  wget -qO- $IMAGE_BUILDER_URL | xz -d | tar x --strip-components=1 -C imagebuilder
fi

sdk/scripts/feeds update -a