#!/bin/sh

# overwrite /etc/config/network
cat > /etc/config/network << EOF
config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fd97:28f0:4724::/48'

config interface 'lan'
	option proto 'static'
	option netmask '255.255.255.0'
	option ipaddr '192.168.10.1'

config interface 'wwan'
	option proto 'dhcp'
EOF

# overwrite /etc/config/wireless
cat > /etc/config/wireless << EOF
config wifi-device 'radio0'
	option type 'mac80211'
	option channel '11'
	option hwmode '11g'
	option path 'platform/10300000.wmac'
	option htmode 'HT20'

config wifi-iface 'ap'
	option device 'radio0'
	option network 'lan'
	option mode 'ap'
	option ssid 'Doodle3D'
	option key '1234567890'
	option encryption 'psk2'

config wifi-iface 'sta'
	option device 'radio0'
	option network 'wwan'
	option mode 'sta'
	option ssid ''
	option key ''
	option encryption 'psk2'
	option disabled '1'
EOF

# Make webserver accessible from WAN / WWAN
cat >> /etc/config/firewall << EOF
config redirect
	option src wan
	option src_dport 80
	option proto tcp
	option dest lan
	option dest_ip 192.168.10.1
EOF

# dhcp
uci set dhcp.@dnsmasq[0].rebind_protection=0

# firewall
uci add_list firewall.@zone[1].network=wwan    # zone 1 should be the zone with name 'wan'

# uhttpd
uci add_list uhttpd.main.interpreter=".php=/usr/bin/php-cgi"  # unfortunately this removes all comments from /etc/config/uhttpd
uci set uhttpd.main.index_page="index.html index.php"

# hostname
uci set system.@system[0].hostname=Doodle3D

# save settings
uci commit

exit 0


